from typing import Protocol

from planner.domain.pose import WorldPose
from planner.domain.trajectory import MotionSegment


class Vehicle(Protocol):
    def current_pose(self) -> WorldPose: ...
    def execute_segment(self, segment: MotionSegment) -> None: ...
    def cancel(self) -> None: ...
    def hover(self) -> None: ...
    def collision_state(self) -> bool: ...

